### ISSUE TITLE
Can't get it to work 

### ISSUE THREAD

**Issue by fredyates** [heysketch/sketch-color-picker-plus#3]
This has been one of my biggest wants for Sketch since I started using it as my primary UI Design tool six months ago. I've posted on reddit, forums, twitter, but until today found nothing. I was elated to see someone made the plugin.

However, I can't get it to work at all. I've tried installing it manually, through Sketch Toolbox, deleting all other plugins, restarting Sketch, any combination of all of those, but no matter what I do I can't seem to get it to work. Neither the keyboard shortcut or clicking on the option manually from the menu will product the color picker. I have a few custom shortcuts through the OSX Keyboard Shortcuts interface but none of them are Ctrl Shift C so I don't think they're conflicting.

I'm on 3.3.3. Any help would be appreciated so much as this is one of my biggest pain points.

Thanks!

**Comment by turbobabr** [comment]
Hey Fred! 
I can feel your pain! :)

Could you please check plugins context menu, whether it contains `Run 'Pick Border Color' again` after you hit `control-shift-c`?

![bitmap](https://cloud.githubusercontent.com/assets/6356526/10700149/fc67d156-79e5-11e5-9f7b-674b9ea6f747.png)

**Comment by turbobabr** [comment]
Hm... also - are you on El Cap?

**Comment by turbobabr** [comment]
It think you use OSX 10.10 and today I found out that it doesn't work for Yosemite. This bug was fixed - try to reinstall plugin.
