### ISSUE TITLE
Not working on 3.4

### ISSUE THREAD

**Issue by rorysmyth** [heysketch/sketch-color-picker-plus#4]
Triggering it from the menu doesn't work either. Ideas?

**Comment by turbobabr** [comment]
Did it work in 3.3 before?

**Comment by rorysmyth** [comment]
it did yes. And it was glorious

**Comment by turbobabr** [comment]
Today, I found out that the plugin didn't work on Yosemite, but it doesn't explain why it worked in 3.3 and stopped work for you in 3.4. Probably, you use different systems. Anyway, the fix is ready - try to re-install plugin - probably, it'll solve the issue.
