### ISSUE TITLE
Installed your plugin, will cause the collapse of the sketch, too much memory footprint

### ISSUE THREAD

**Issue by hi-caicai** [heysketch/sketch-color-picker-plus#6]
![2015-11-12 4 49 38](https://cloud.githubusercontent.com/assets/1811819/11115163/9340d43c-8964-11e5-8a9f-c1b1ffd80a6e.png)

sketch Version 3.4.2 (15848)

**Comment by hi-caicai** [comment]
Maybe it is sketch‘s  problem

**Comment by turbobabr** [comment]
I can't reproduce the crash. Did it happen only once?

**Comment by hi-caicai** [comment]
I am so sorry,At last I found it was sketch's problem....., When I delete the plugin , The sketch stop work again..
